repos:
   - repo: https://github.com/pre-commit/mirrors-eslint
     rev: "v8.55.0" # Use the sha / tag you want to point at
     hooks:
        - id: eslint
          files: \.[t]sx?$ # *.js, *.jsx, *.ts and *.tsx
          types: [file]
